import { Book } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import Link from "next/link";
import { BackButton } from "../../components/BackButton";

const Book: NextPage = () => {
  const [book, setBook] = useState<Book>();
  const [isLoading, setIsLoading] = useState(false);

  const router = useRouter();

  useEffect(() => {
    setIsLoading(true);
    if (!router.isReady) return;
    const { bookid } = router.query;
    fetch(`/api/book/${bookid}`)
      .then((res) => res.json())
      .then((book) => {
        setBook(book);
        setIsLoading(false);
      });
  }, [router.isReady]);

  if (isLoading) return <p>Loading...</p>;
  if (!book) return <p>No book data</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BackButton />
        <h1 className={styles.title}>{book.title}</h1>
        <p>{book.author}</p>
        <Link href={`/book/${book.id}/edit`}>
          <button>Edit</button>
        </Link>
        <form method="post" action={`/api/book/${book.id}/delete`}>
          <input type="submit" value="Delete" />
        </form>
      </main>
    </div>
  );
};

export default Book;
