import { Book } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";

const Book: NextPage = () => {
  const [bookData, setBookData] = useState<Book>();
  const [isLoading, setIsLoading] = useState(false);

  const router = useRouter();

  useEffect(() => {
    setIsLoading(true);
    if (!router.isReady) return;
    const { bookid } = router.query;
    fetch(`/api/book/${bookid}`)
      .then((res) => res.json())
      .then((bookData) => {
        setBookData(bookData);
        setIsLoading(false);
      });
  }, [router.isReady]);

  if (isLoading) return <p>Loading...</p>;
  if (!bookData) return <p>No book data</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{bookData.title}</h1>
      </main>
    </div>
  );
};

export default Book;
