import { Book } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { useSession, signIn, signOut } from "next-auth/react";
import styles from "../../styles/Home.module.css";
import { BackButton } from "../../components/BackButton";
import buttonStyles from "../../styles/Button.module.css";
import { SignedIn } from "../../components/SignedIn";

const Book: NextPage = () => {
  const [book, setBook] = useState<Book>();
  const [isLoading, setIsLoading] = useState(false);
  const { data: session } = useSession();

  const router = useRouter();

  useEffect(() => {
    setIsLoading(true);
    if (!router.isReady) return;
    const { bookid } = router.query;
    fetch(`/api/book/${bookid}`)
      .then((res) => res.json())
      .then((book) => {
        setBook(book);
        setIsLoading(false);
      });
  }, [router.isReady]);

  if (session) {
    if (isLoading) return <p>Loading...</p>;
    if (!book) return <p>No book data</p>;

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {session.user && session.user.email ? (
            <SignedIn email={session.user.email} />
          ) : (
            ""
          )}
          <BackButton />
          <h1 className={styles.title}>{book.title}</h1>
          <p>{book.author}</p>
          <div className={styles.buttonContainer}>
            <Link href={`/book/${book.id}/edit`}>
              <button className={buttonStyles.button}>Edit</button>
            </Link>
            <form method="post" action={`/api/book/${book.id}/delete`}>
              <input
                className={buttonStyles.button}
                type="submit"
                value="Delete"
              />
            </form>
          </div>
        </main>
      </div>
    );
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
};

export default Book;
