import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import styles from "../../styles/Form.module.css";
import buttonStyles from "../../styles/Button.module.css";
import { SignedIn } from "../../components/SignedIn";
import { SignedOut } from "../../components/SignedOut";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {session.user && session.user.email ? (
            <SignedIn email={session.user.email} />
          ) : (
            ""
          )}
          <form method="post" action="/api/book/create" className={styles.form}>
            <label>Title:</label>
            <input name="title" type="text" />
            <label>Author:</label>
            <input name="author" type="text" />
            <input className={buttonStyles.button} type="submit" value="Save" />
          </form>
        </main>
      </div>
    );
  }
  return (
    <main className={styles.main}>
      <SignedOut />
    </main>
  );
};

export default Home;
