import { Book } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Card } from "../components/Card";
import styles from "../styles/Home.module.css";
import buttonStyles from "../styles/Button.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const [books, setBooks] = useState<Book[]>();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    fetch("api/books")
      .then((res) => res.json())
      .then((books) => {
        setBooks(books);
        setIsLoading(false);
      });
  }, []);

  if (session) {
    if (isLoading) return <p>Loading...</p>;
    if (!books) return <p>No book data</p>;
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          Signed in as {session.user?.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
          <h1 className={styles.title}>Book List</h1>
          <div className={styles.bookList}>
            {books.map(({ id, title, author }) => (
              <Card key={id} id={id} title={title} author={author} />
            ))}
            <Link href="/book/create">
              <button className={buttonStyles.button}>Create new book</button>
            </Link>
          </div>
        </main>
      </div>
    );
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
};

export default Home;
